### ISSUE TITLE
Master Security Group Rule Does Not Match Terraform Configuration

### ISSUE THREAD

**Issue by asafpelegcodes** [terraform-aws-modules/terraform-aws-emr#10]
## Description

I have attempted to add a specific rule for auto-generated master security group to allow SSH access. The rule is to allow port 22 access from anything on the internal network of my VPC. However, the result in AWS shows that it is open to all ports, not just 22.

I have the following section in my module configuration
```hcl
master_security_group_rules = {
    "default" : {
      "cidr_blocks" : [
        "0.0.0.0/0"
      ],
      "description" : "Allow all egress traffic",
      "from_port" : 0,
      "ipv6_cidr_blocks" : [
        "::/0"
      ],
      "protocol" : "-1",
      "to_port" : 0,
      "type" : "egress"
    },
    "ssh_access" : {
      "cidr_blocks" : [data.terraform_remote_state.shared_state.outputs.shared_vpc_cidr],
      "description" : "Allow ssh traffic",
      "from_port" : 22,
      "ipv6_cidr_blocks" : ["::/0"],
      "protocol" : "-1",
      "to_port" : 22,
      "type" : "ingress"
    }
  }
```
Here is a screen shot of the respective SG ingress table.
<img width="1192" alt="Screen Shot 2023-06-22 at 9 49 33 PM" src="https://github.com/terraform-aws-modules/terraform-aws-emr/assets/6590390/6bcc9d83-eba0-4152-a663-82b77f8ddb59">

As you can see it created the rule but for every port, not just 22.

The terraform state for the rule looks correct...
```json
{
    "index_key": "ssh_access",
    "schema_version": 2,
    "attributes": {
      "cidr_blocks": [
        "10.3.0.0/16"
      ],
      "description": "Allow ssh traffic",
      "from_port": 22,
      "id": "sgrule-4093924578",
      "ipv6_cidr_blocks": [
        "::/0"
      ],
      "prefix_list_ids": null,
      "protocol": "-1",
      "security_group_id": "sg-04d6a320e7f0178ca",
      "security_group_rule_id": "",
      "self": false,
      "source_security_group_id": null,
      "timeouts": null,
      "to_port": 22,
      "type": "ingress"
    },
    "sensitive_attributes": [],
    "dependencies": [
      "data.aws_vpc.vpc",
      "data.terraform_remote_state.shared_state",
      "module.emr.aws_security_group.master"
    ]
  }
]
    }
```
The state for the security group itself does match what is in AWS but it doesn't match the rule...
```json
"ingress": [
    {
      "cidr_blocks": [
        "10.3.0.0/16"
      ],
      "description": "Allow ssh traffic",
      "from_port": 0,
      "ipv6_cidr_blocks": [
        "::/0"
      ],
      "prefix_list_ids": [],
      "protocol": "-1",
      "security_groups": [],
      "self": false,
      "to_port": 0
    }
...
]
```
## Versions

- Module version [Required]: 1.0.0

- Terraform version: 1.4.6
- Provider version(s): AWS v5.5.0

## Reproduction Code [Required]

See above, using code that closely follows the private instance_groups https://github.com/terraform-aws-modules/terraform-aws-emr#private-cluster-w-instance-group

I am using terraform cloud with workspaces

## Expected behavior

The SSH rule should be just port 22

## Actual behavior

The SSH rule is all ports

### Terminal Output Screenshot(s)

<img width="614" alt="Screen Shot 2023-06-22 at 10 05 06 PM" src="https://github.com/terraform-aws-modules/terraform-aws-emr/assets/6590390/42c2b3e2-85cf-4a46-9a65-dbc07e33e739">

**Comment by bryantbiggs** [comment]
Your syntax is incorrect and you have all IPc6 in the CIDR block. Please try below:

```hcl
locals {
  master_security_group_rules = {
    default = {
      cidr_blocks      = ["0.0.0.0/0"],
      description      = "Allow all egress traffic",
      from_port        = 0,
      ipv6_cidr_blocks = ["::/0"],
      protocol         = "-1",
      to_port          = 0,
      type             = "egress"
    }
    ssh_access = {
      cidr_blocks = [data.terraform_remote_state.shared_state.outputs.shared_vpc_cidr],
      description = "Allow ssh traffic",
      from_port   = 22,
      protocol    = "tcp",
      to_port     = 22,
      type        = "ingress"
    }
  }
}
```

**Comment by bryantbiggs** [comment]
closing with guidance provided above - please feel free to respond if still facing issues
