### ISSUE TITLE
Insufficient Role/Rolebinding for EMR on EKS Virtual Cluster

### ISSUE THREAD

**Issue by youngjeong46** [terraform-aws-modules/terraform-aws-emr#11]
## Description

The `virtual-cluster` module defines a set of policy rules for the Role and Rolebindings [here](https://github.com/terraform-aws-modules/terraform-aws-emr/blob/master/modules/virtual-cluster/main.tf#L63). It is missing some rules when compared to the official AWS documentations [here](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html#setting-up-cluster-access-manual). Namely:

- apiGroups: [""]
   resources: ["persistentvolumeclaims"] 
   verbs: ["get", "list", "watch", "describe", "create", "edit", "delete", "annotate", "patch", "label"]
- apiGroups: ["networking.k8s.io"] 
   resources: ["ingresses"]
   verbs: ["get", "list", "watch", "describe", "create", "edit", "delete", "annotate", "patch", "label"]

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:

- Terraform version:
Terraform v1.4.2
- Provider version(s):

+ provider registry.terraform.io/hashicorp/aws v5.8.0

## Reproduction Code [Required]

1. `git clone https://github.com/terraform-aws-modules/terraform-aws-emr`

## Expected behavior

The resource `kubernetes_role_v1` in `modules/virtual-cluster/main.tf` is expected to include all of the rules listed [here](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-cluster-access.html#setting-up-cluster-access-manual).

## Actual behavior

The resource is missing a couple of rules.

**Comment by bryantbiggs** [comment]
thanks @youngjeong46 - are you interested in submitting a PR for this or should we take on this change?

**Comment by youngjeong46** [comment]
I'll submit a PR.

**Comment by bryantbiggs** [comment]
resolved in #12
