### ISSUE TITLE
ebs_config could not take effect

### ISSUE THREAD

**Issue by wbb1975** [terraform-aws-modules/terraform-aws-emr#19]
## Description

If you specifiy ebs_config in core_instance_fleet section, it will be ignore when running "terraform plan", for example:
core_instance_fleet = {
    name                      = "core fleet"
    target_on_demand_capacity = 10

    instance_type_configs = [
      {
        bid_price_as_percentage_of_on_demand_price = 100
        ebs_config = 
          {
            size                 = 256
            iops                 = 4000
            type                 = "gp3"
            volumes_per_instance = 4
          }
        instance_type     = "r6a.2xlarge"
        weighted_capacity = 1
      }
    ]
    launch_specifications = {
      on_demand_specification = {
        allocation_strategy = "lowest-price"
      }
    }
  }
will output:
 + core_instance_fleet {
          + id                             = (known after apply)
          + name                           = "core fleet"
          + provisioned_on_demand_capacity = (known after apply)
          + provisioned_spot_capacity      = (known after apply)
          + target_on_demand_capacity      = 10
          + target_spot_capacity           = 0

          + instance_type_configs {
              + bid_price_as_percentage_of_on_demand_price = 100
              + instance_type                              = "r6a.2xlarge"
              + weighted_capacity                          = 1

              + ebs_config {
                  + size                 = 64
                  + type                 = "gp3"
                  + volumes_per_instance = 1
                }
            }

          + launch_specifications {
              + on_demand_specification {
                  + allocation_strategy = "lowest-price"
                }
            }
        }
  The output EBS storage is just 64G. Obviously it's not expected.

  When I  changed it into:
  core_instance_fleet = {
    name                      = "core fleet"
    target_on_demand_capacity = 10

    instance_type_configs = [
      {
        bid_price_as_percentage_of_on_demand_price = 100
        ebs_config = **[**
          {
            size                 = 256
            iops                 = 4000
            type                 = "gp3"
            volumes_per_instance = 4
          }
        **]**
        instance_type     = "r6a.2xlarge"
        weighted_capacity = 1
      }
    ]
    launch_specifications = {
      on_demand_specification = {
        allocation_strategy = "lowest-price"
      }
    }
  }

terraform plan will output:
 core_instance_fleet {
          + id                             = (known after apply)
          + name                           = "core fleet"
          + provisioned_on_demand_capacity = (known after apply)
          + provisioned_spot_capacity      = (known after apply)
          + target_on_demand_capacity      = 10
          + target_spot_capacity           = 0

          + instance_type_configs {
              + bid_price_as_percentage_of_on_demand_price = 100
              + instance_type                              = "r6a.2xlarge"
              + weighted_capacity                          = 1

              **+ ebs_config {
                  + iops                 = 4000
                  + size                 = 256
                  + type                 = "gp3"
                  + volumes_per_instance = 4
                }**
            }

          + launch_specifications {
              + on_demand_specification {
                  + allocation_strategy = "lowest-price"
                }
            }
        }

 Although plan 256 GB, but after EMR Cluster is created, you will noticed that it in fact also just has 64 G EBS Storage.

## Versions

- Module version [Required]: 
  source                      = "terraform-aws-modules/emr/aws"
  version                     = "1.2.2"

- Terraform version:
  terraform --version
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.7.5. You can update by downloading from https://www.terraform.io/downloads.html
- Provider version(s):
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v5.31.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.7.5. You can update by downloading from https://www.terraform.io/downloads.html

## Reproduction Code [Required]

Please refer to above terarform snippet.

I use S3 as the backend.
terraform init -backend-config=backend.config
terraform plan
terraform apply

## Expected behavior

EC2 in setup EMR CLuster has EBS storage of 256 GB other than 64 GB.

## Actual behavior

EC2 in setup EMR CLuster has EBS storage of  64 GB.

**Comment by AkshayDubey29** [comment]
We are also facing the same issue, it seems.

**Comment by bryantbiggs** [comment]
I've opened a PR to update the examples to show the correct syntax - however, please checkout the note https://github.com/terraform-aws-modules/terraform-aws-emr/pull/20#issue-2225791964 - I would suggest opening a ticket on the upstream AWS provider to have this fixed there

**Comment by antonbabenko** [comment]
This issue has been resolved in version 2.0.0 :tada:

**Comment by wbb1975** [comment]
Thank you @antonbabenko
