### ISSUE TITLE
EMR service is recreating on every terraform apply

### ISSUE THREAD

**Issue by Durgaprasad-Polavarapu** [terraform-aws-modules/terraform-aws-emr#24]
## Versions

- Module version [Required]:
v2.1.0
- Terraform version:
 1.5.3
- Provider version(s):
~> 5.44
## Expected behavior

Everytime terraform apply is triggered emr service is getting recreated, using  release_label = "emr-6.13.0" but still recreating with same version, my understanding is that when release_label is used it should not check for newer version

## Actual behavior

 release_label is forcing replacing of emr service

![image](https://github.com/terraform-aws-modules/terraform-aws-emr/assets/87110962/762c5b3d-7bd5-4344-a0ed-f0fcde38109c)

**Comment by bryantbiggs** [comment]
You can set the release version with `release_label`, otherwise this module will pull the latest release version at the time of apply

**Comment by Durgaprasad-Polavarapu** [comment]
> You can set the release version with `release_label`, otherwise this module will pull the latest release version at the time of apply

i'm setting release_label, yet emr is recreating for every terraform apply, could you please try to reproduce this? this is taken from example code

this is how i'm pass release_label

  source  = "terraform-aws-modules/emr/aws"
  version = "v2.1.0"

  autoscaling_iam_role_description = "IAM role for EMR AutoScaling ${local.resource_prefix}"

  name = "emr-instance-group"

  release_label = "emr-6.13.0"
  applications  = ["Flink"]
